### PR TITLE
OLMIS-7762: (WIP) Bugfix for authentication from superset to openlmis

### PR DESCRIPTION
**Pull request by pwargulak**

### CODE REVIEW

**Review by anawrotsoldevelo — APPROVED** [review]

**Comment by pgesek** [comment]
@pwargulak if this works - can we use a repo in the OLMIS org (we can create a new one), instead a private fork?

**Comment by pwargulak** [comment]
@pgesek There is already a fork for openlmis - I have no rights to push any branch there so I've sued my private for now.

**Comment by pgesek** [comment]
You mean this repo https://github.com/OpenLMIS/superset-patchup ?

I see your commit on top... 

I think I have at least write rights there, so if you do a PR I can merge it

**Comment by pwargulak** [comment]
@pgesek Yes, if this works I'll make a PR there and use that repo

**Pull request merged**
