### PR TITLE
test auth

### PR DESCRIPTION
**Pull request by Wambere**

### CODE REVIEW

**Comment by craigappl** [comment]
@Wambere and @jasonrogena , I got the nginx service up and running locally, it asks for the password when I go to the URL that's defined in the settings.env file (192.168.1.141/nifi) 

Here's what I had to change:
* The settings.env file in the parent directory didn't correctly create the env variables for NGINX_BASIC_AUTH_USER so I moved them to the .env file in the reporting directory
* The password was stored in plaintext and that didn't work when trying to login. So, I used openssl to encrypt the password in the nginX container on startup
* I changed the password filename to start with a dot .htpasswd to follow best practice

Note: It doesn't work when I navigate to localhost:8080/nifi because that's consul's internal URL that doesn't have enable_basic_auth on it. The auth will only pop-up on requests from upstream.

I wasn't able to test this to verify that superset doesn't ask for a password from nGinX. @jasonrogena or @Wambere , can you test this piece?

**Comment by jasonrogena** [comment]
@craigappl this isn't done yet. I should have probably marked it with a "Do Not Merge".

**Comment by jasonrogena** [comment]
Thanks @craigappl

**Comment by craigappl** [comment]
@jasonrogena can you test to make sure that it doesn't affect Superset?

I'm not able to test it because I can't get nifi.local or superset.local to register on my dev machine. Are there instructions on setting up a local DNS to register those URLs in Firefox?

**Pull request merged**
