### PR TITLE
NiFi And Superset Over HTTPS

### PR DESCRIPTION
**Pull request by jasonrogena**
Add a NGINX container in the reporting docker-compose that adds support for accessing NiFi and Superset over HTTPS.

### CODE REVIEW

**Comment by craigappl** [comment]
@jasonrogena  I won't be able to test this until I get back in the US.

**Comment by craigappl** [comment]
@jasonrogena  I ran docker-compose up without SSL enabled and the services stand up without HTTPS as expected. I haven't yet tried with a SSL cert. Right now, the config container is complaining because curl isn't installed

"config-container_1 | sh: curl: not found"

**Comment by jasonrogena** [comment]
@craigappl did you run `docker-compose down -v` before running `docker-compose up --build` after pulling the changes? You need to do both. `--build` with docker-compose up should install curl in the config container.

**Comment by craigappl** [comment]
@jasonrogena Everything's working on localhost. Squashing and merging.

**Pull request merged**
